#!/bin/sh
echo "#EXTM3U" > "$2" || exit 1
data=$(youtube-dl -ix --get-duration --get-title --get-url "$1")
i=0
IFS=$'\n'
for line in $data; do
    case $i in
        0)
            name="$line"
            ;;
        1)
            url="$line"
            ;;
        2)
            sec=${line##*:}

            if [[ $line =~ ":" ]]; then
                line=${line%:*}
                min=${line##*:};
            else
                min=00
            fi

            if [[ $line =~ ":" ]]; then
                line=${line%:*}
                hour=${line%:*}
            else
                hour=00
            fi

            echo "#EXTINF:$(( ${hour#0} * 3600 + ${min#0} * 60 + ${sec#0} )),$name" >> "$2"
            echo "$url" >> "$2"
            ;;
    esac
    i=$(( (i+1) % 3 ))
done
